config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'
  resources :recipes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord

    def light?
        calories < 100
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    def index
        @recipes = Recipe.all
    end

    def show
        @recipe = Recipe.find(params[:id])

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

    def formata_caloria(recipe)
        if recipe.light?
            content_tag(:strong, "Light (menos de 100 calorias)")
        else
            recipe.calories
        end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receitasnet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1><%=pluralize(@recipes.size, "Receita", "Receitas")%></h1>

    <% @recipes.each do |recipe| %>
        <article>
            <header>
              <h2><%= link_to recipe.name , recipes %></h2>
            <header>
         <p>  
            <%= truncate(recipe.stuff, length:15, separator:' ') %>
         </p>
         <p>
            <%= formata_caloria(recipe) %>
         </p>
         <table>
            <tr>
                <th>Modo de preparo: </th>
                <td><%= recipe.prepare_mode %></td>
            </tr>
            <th>Custo do Prato:</th>
                <td><%= number_to_currency(recipe.cost) %></td>
            </tr>
         </table>
        </article>
    <%end %>

app/views/recipes/show.html.erb
<article>
  <header>
    <h1> <%= @recipe.name %></h1>
  </header>
  <h2>Ingredientes</h2>
  <p>
    <%= @recipe.stuff %>
  </p>
  <h2>Calorias</h2>
  <p>
    <%= @recipe.calories %>
  </p>
  <h3>Modo de Preparo</h3>
  <p>
    <%= @recipe.prepare_mode %>
  </p>
  <h3>Custo</h3>
  <p>
    <%= @recipe.cost %>
  </p>
</article>

<%= link_to "Receitas", recipes_path %>